### ISSUE TITLE
WinCE bat files have the wrong path to c:\CE

### ISSUE THREAD

**Issue by lanspeed** [greycookie/86Duino_DuinOS#1]

**Comment by lanspeed** [comment]
The followings bat files have the wrong CE Path:
Please replac C:\CE**\*   to C:\WinCE***
CE_ONE.BAT
CE_ECAKE.BAT
CE_ONE_V.BAT
CE_ZERO.BAT

**Comment by greycookie** [comment]
Thanks for your report.The bug is fixed.
